name: keepalive-skillboard-preparation

on:
  schedule:
    - cron: "*/10 * * * *"    # toutes les 10 minutes
  workflow_dispatch:           # permet de lancer manuellement si besoin

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /healthz (GET)
        run: |
          curl -sS --max-time 30 https://skillboard-preparation.onrender.com/healthz -o /dev/null -w "%{http_code}\n"
